name: Move pull requests into Being reviewed

on:
  pull_request:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Task Central
          column: Being reviewed
          repo-token: ${{ secrets.ORGANIZATION_PROJECT_TOKEN }}
